### ISSUE TITLE
Vandium not working with firebase

### ISSUE THREAD

**Issue by jaxkodex** [vandium-io/vandium-node#64]
I've just started using Vandium to create a simple app that has firebase as a backend database. I am using plain js, Vandium as the lambda framework and aws sam as deployment tool.

I encountered a problem when adding Vandium to the project since importing it makes firebase fail with an error `Cannot read property 'readFileSync' of null` that I haven't manage to solve.

I created a clean project [here](https://github.com/jaxkodex/vandium-firebase-test) where I have 2 handlers `index.js` and `index_vandium.js` the only different is that the later includes vandium `const vandium = require('vandium')` at line 16.

Any hint on why this could be happening?

**Comment by richardhyatt** [comment]
Do you have a stack trace for the failed call to `readFileSync`? Is the exception happening with tests when running on AWS? Your devDependencies should contain the aws-sdk as vandium has the ability to make ssm calls to get parameters (better way to store secrets than using .env in my opinion)

On Jan 1, 2020, at 10:03, Jorge Vilca <notifications@github.com> wrote:

﻿

I've just started using Vandium to create a simple app that has firebase as a backend database. I am using plain js, Vandium as the lambda framework and aws sam as deployment tool.

I encountered a problem when adding Vandium to the project since importing it makes firebase fail with an error Cannot read property 'readFileSync' of null that I haven't manage to solve.

I created a clean project here<https://github.com/jaxkodex/vandium-firebase-test> where I have 2 handlers index.js and index_vandium.js the only different is that the later includes vandium const vandium = require('vandium') at line 16.

Any hint on why this could be happening?

**Comment by jaxkodex** [comment]
Thanks for the quick response, the strack trace looks like this:

```
TypeError: Cannot read property 'readFileSync' of null
    at fetch (/var/task/node_modules/protobufjs/src/root.js:160:34)
    at Root.load (/var/task/node_modules/protobufjs/src/root.js:194:13)
    at Root.loadSync (/var/task/node_modules/protobufjs/src/root.js:235:17)
 at Object.loadSync (/var/task/node_modules/protobufjs/src/index-light.js:69:17)
    at Object.<anonymous> (/var/task/node_modules/@grpc/proto-loader/build/src/index.js:235:37)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
```

The lambda function works on AWS if I call the `index.js` handler, if I configure it to call `index_vandium.js` it fails.

I'll checkout SSM, had not hear of it before, thanks!

**Comment by richardhyatt** [comment]
Any update on this issue?

I've tried running your code from the test repo and I could not reproduce the error in my environment. Does the issue happen on load or on execution of the lambda?

Few things to try:
* Try putting `process.env.VANDIUM_PREVENT_EVAL = 'false';` at the top of your file, which will prevent vandium from blocking calls to `eval()`
*  The code `var serviceAccount = require(path.resolve(process.env.FIREBASE_CREDENTIALS))` (index.js:6) is probably not the best way to load credentials. Might be better to use a static name and make it `const` rather than `var`

**Comment by jaxkodex** [comment]
Hello, the lambda works when added `process.env.VANDIUM_PREVENT_EVAL = 'false';` so I modified my sam template.yaml to have a Globals section:

```
Globals:
  Function:
    Runtime: nodejs12.x
    Environment:
      Variables:
        VANDIUM_PREVENT_EVAL: false
```

Am I missing something when using prevent eval false? didn't get to find this variable on the documentation.

Thanks.

**Comment by richardhyatt** [comment]
Vandium 6.0 is now available and the VANDIUM_PREVEN_EVAL is automatically set to false.

**Comment by jaxkodex** [comment]
With version 6.0 the service works as expected. Thanks
